import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Gideon_Roman,
  Nanum_Myeongjo,
} from "next/font/google";
import "../style/globals.scss";
import { Provider } from "jotai";
import Modal from "@/components/Modal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gideonRoman = Gideon_Roman({
  variable: "--font-gideon-roman",
  subsets: ["latin"],
  weight: "400",
});

const nanumMyeongjo = Nanum_Myeongjo({
  variable: "--font-nanum-myeongjo",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gideonRoman.variable} ${nanumMyeongjo.variable}`}
      >
        <Provider>
          <main className="root-main-container">{children}</main>
          <Modal />
        </Provider>
      </body>
    </html>
  );
}
