import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Gideon_Roman,
  Nanum_Myeongjo,
} from "next/font/google";
import "../style/globals.scss";
import { Provider } from "jotai";
import Modal from "@/components/Modal";
import GlobalImagePreloader from "@/components/GlobalImagePreloader";
import ImagePrefetchLoader from "@/components/ImagePrefetchLoader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gideonRoman = Gideon_Roman({
  variable: "--font-gideon-roman",
  subsets: ["latin"],
  weight: "400",
});

const nanumMyeongjo = Nanum_Myeongjo({
  variable: "--font-nanum-myeongjo",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gideonRoman.variable} ${nanumMyeongjo.variable}`}
      >
        <Provider>
          <ImagePrefetchLoader
            fallback={
              <div className="text-center">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
                <h2 className="text-xl font-semibold mt-4">앱 로딩 중...</h2>
              </div>
            }
          >
            <main className="root-main-container">{children}</main>
            <Modal />
          </ImagePrefetchLoader>
        </Provider>
      </body>
    </html>
  );
}
